# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      echo "Desplegando contenido..."
      az storage blob upload-batch -d '$web' -s dist/
    displayName: 'Desplegar a Azure Blob Static Website'
